### ISSUE TITLE
Wondering if this is working

### ISSUE THREAD

**Issue by glottisfaun0000** [LumenwoodGarden/e-hentai-rss#1]
Contents of my feeds.txt:
```parody;parody```

Output of ```python3 main.py parody```:
```Traceback (most recent call last):
  File "main.py", line 163, in <module>
    main()
  File "main.py", line 110, in main
    feedFile = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: 'parody'
```
Output of ```python3 main.py feeds.txt parody```:
```
couldn't find a matching feed in feeds.txt
```

**Comment by LumenwoodGarden** [comment]
sorry, the readme is a little out-dated, recently changed that the location of the feeds.txt can passed as the second argument to main.py
Tho idk why your line 110 in main.py is `feedFile = open(sys.argv[1])` instead of `feedFile = open(sys.argv[2])`
The new way to generate a feed is `python3 main.py feed-name path/to/feeds.txt`
